main_task:
  container:
    image: rust:latest
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cargo update && cat Cargo.lock
  build_script: cargo build --all
  test_script: cargo test --all
  before_cache_script: rm -rf $CARGO_HOME/registry/index

clean_task:
  container:
    image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

clippy_task:
  container:
    image: rustlang/rust:nightly
  # Allowed to fail with missing clippy, or other issues by newly introduced
  # lints that would break API stability (which happens sometimes).
  allow_failures: true
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features -- -D warnings

release_task:
  only_if: $CIRRUS_BRANCH =~ 'release-.*'
  container:
    image: rust:latest
  script: ./release_checks

doc_task:
  container:
    image: rustlang/rust:nightly
  script: cargo doc --no-deps --document-private-items --all-features
