[package]
name = "cargo-supply-chain"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"
license = "Apache-2.0 OR MIT OR Zlib"

[dependencies]
cargo_metadata = "0.11.3"
crates_io_api = "0.6.1"
